#!/usr/bin/env bash
set -euo pipefail
source_root=$(cd "$(dirname "$0")/../.." && pwd)
historical_tip=0898b29513b58e5cd3ba13d0c13211892162a8a7
merge_count=$(git -C "$source_root" log --merges --first-parent "$historical_tip" --format='%s' | awk '/^Merge MW-[0-9]+:/{count++} END{print count+0}')
row_count=$(awk '/^\| 20[0-9][0-9]-/ && / \| merge.sh:/{count++} END{print count+0}' "$source_root/docs/factory/merges.md")
if [[ "$row_count" -ne "$merge_count" ]]; then
    echo "FAIL historical merge log: $row_count rows for $merge_count Merge MW- commits" >&2
    exit 1
fi
echo "PASS historical merge log: $row_count rows"
repo=$(mktemp -d)
trap 'rm -rf "$repo"' EXIT
cd "$repo"
git init -q -b main
git config user.email test@example.com
git config user.name Test
git config core.autocrlf true
mkdir -p scripts/factory frontend/convex/_generated .venv/bin mockbin
cp "$source_root/.gitattributes" .gitattributes
cp "$source_root/scripts/factory-merge.sh" scripts/factory-merge.sh
cat > scripts/factory/lin.py <<'PY'
import os
import sys
if sys.argv[1] == "ready":
    reason = os.environ.get("MOCK_REFUSAL")
    if reason:
        raise SystemExit("factory: MW-999 " + reason)
    print('{"approver":"Daryl, in chat, 2 Oct 2026"}')
PY
printf 'base\n' > file.txt
printf 'original\n' > frontend/convex/_generated/api.d.ts
printf 'base\n' > frontend/convex/example.ts
cat > .venv/bin/python <<'SH'
#!/usr/bin/env bash
exit 0
SH
cat > mockbin/npm <<'SH'
#!/usr/bin/env bash
if [[ $1 == run && $2 == build ]]; then
    printf 'regenerated by build\n' > convex/_generated/api.d.ts
    printf 'new\n' > convex/_generated/build.d.ts
fi
SH
cat > mockbin/npx <<'SH'
#!/usr/bin/env bash
if [[ $1 == convex && $2 == deploy ]]; then
    printf 'regenerated by deploy\n' > convex/_generated/api.d.ts
    printf 'new\n' > convex/_generated/deploy.d.ts
    if [[ ${MOCK_OTHER_CHANGE:-} == 1 ]]; then
        printf 'changed by deploy\n' > ../file.txt
    fi
fi
SH
cat > mockbin/git <<'SH'
#!/usr/bin/env bash
if [[ $1 == push ]]; then
    echo 'mock push reached after clean checks' >&2
    exit 1
fi
exec "$REAL_GIT" "$@"
SH
chmod +x .venv/bin/python mockbin/*
git add .
git add --renormalize .
git commit -qm base
git checkout-index -f -- scripts/factory-merge.sh scripts/factory/lin.py
if file scripts/factory-merge.sh scripts/factory/lin.py | grep -q CRLF; then
    echo 'FAIL shell or Python checkout has CRLF' >&2
    exit 1
fi
echo 'PASS shell and Python checkout use LF with core.autocrlf=true'
git branch wave1-demo-ready
git update-ref refs/remotes/origin/main "$(git rev-parse main)"
git update-ref refs/remotes/origin/wave1-demo-ready "$(git rev-parse wave1-demo-ready)"
git branch factory/MW-999
git checkout -q factory/MW-999
printf 'changed\n' > frontend/convex/example.ts
git add frontend/convex/example.ts
git commit -qm 'Change Convex function'
git checkout -q main
sha=$(git rev-parse factory/MW-999)
refuse() {
    local name=$1 expected=$2
    shift 2
    if output=$("$@" 2>&1); then
        echo "FAIL $name: merge gate accepted invalid input" >&2
        exit 1
    fi
    if [[ "$output" != *"$expected"* ]]; then
        echo "FAIL $name: $output" >&2
        exit 1
    fi
    echo "PASS $name"
}
refuse wrong-sha 'reviewed SHA' bash scripts/factory-merge.sh MW-999 0000000000000000000000000000000000000000
refuse missing-label 'ready-to-merge' env MOCK_REFUSAL='requires ready-to-merge' bash scripts/factory-merge.sh MW-999 "$sha"
refuse no-approval 'Operator merge approval' env MOCK_REFUSAL='needs Operator merge approval' bash scripts/factory-merge.sh MW-999 "$sha"
refuse old-approval 'after the PASS verdict' env MOCK_REFUSAL='needs Operator merge approval after the PASS verdict' bash scripts/factory-merge.sh MW-999 "$sha"
printf 'dirty\n' >> file.txt
refuse dirty-tree 'main checkout is dirty' bash scripts/factory-merge.sh MW-999 "$sha"
git checkout -- file.txt
real_git=$(command -v git)
refuse generated-restored 'mock push reached after clean checks' env REAL_GIT="$real_git" PATH="$repo/mockbin:$PATH" bash scripts/factory-merge.sh MW-999 "$sha"
[[ -z $(git status --porcelain -- frontend/convex/_generated) ]] || {
    echo 'FAIL generated files were not restored' >&2
    exit 1
}
echo 'PASS build and deploy generated files restored'
git reset -q --hard main
git checkout -q main
refuse deploy-other-change 'Convex deploy changed tracked or untracked files' env MOCK_OTHER_CHANGE=1 REAL_GIT="$real_git" PATH="$repo/mockbin:$PATH" bash scripts/factory-merge.sh MW-999 "$sha"
[[ -z $(git status --porcelain -- frontend/convex/_generated) && $(cat file.txt) == 'changed by deploy' ]] || {
    echo 'FAIL deploy restoration affected unexpected files' >&2
    exit 1
}
echo 'PASS deploy keeps other changes visible to the gate'
